name: Docs

on: 
  release:
    types: [published]

jobs:
  deploy_docs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish Jazzy Docs
      uses: steven0351/publish-jazzy-docs@v1.1.1
      with:
        personal_access_token: ${{ secrets.ACCESS_TOKEN }}
        args: "--module ParsingKit"
